### ISSUE TITLE
CRAN section

### ISSUE THREAD

**Issue by ginberg** [darwin-eu-dev/PaRe#22]
Not sure if this in the scope of the package but we can add a section if a package is on CRAN and since how long. We might also add the package authors (see also #20 for this).  Since if a package is on CRAN we know that it has passed the CRAN review and gives some trust. Some packages that we can use https://www.r-bloggers.com/2019/07/pkginfo-tools-for-retrieving-r-package-information/

**Comment by edward-burn** [comment]
Maybe this could be done in part by having the cran badge (that we use on readme) at the top of the report? 

Then for cran stats, adding number of downloads and number of reverse dependencies would be a useful metric I think

**Comment by mvankessel-EMC** [comment]
I left some comments in the PR.

**Comment by mvankessel-EMC** [comment]
As its been a month, I've closed the PR for now, I'll do the same with this issue
