### ISSUE TITLE
ReportGenerator

### ISSUE THREAD

**Issue by cbarbozaerasmus** [darwin-eu-dev/PaRe#23]
- PaRe::makeReport
- Discuss with package maintainer
- Investigate solution for package

I am getting the following error when running PaRe::makeReport. Do I need to run something else, previous to makeReport?

```
if (interactive()) {
    
    pkgPath <- system.file(package = "ReportGenerator")
    
    outputFile <- tempfile(fileext = ".html")
    
    PaRe::makeReport(pkgPath, outputFile)
}
```

```
Quitting from lines 21-26 (report.Rmd) 
Error in `dplyr::filter()`:
ℹ In argument: `.data$fun %in% .data$name`.
Caused by error in `.data$fun`:
! Column `fun` not found in `.data`.
Backtrace:
  1. ... %>% magick::image_read()
 19. rlang:::abort_data_pronoun(x, call = y)
There were 30 warnings (use warnings() to see them)
```

**Comment by mvankessel-EMC** [comment]
Hi @cbarbozaerasmus,
`system.file(package = "ReportGenerator")` points to the installed, compiled package in your package library. PaRe does not expect this input. PaRe expects the uncompiled R package project.

If you open the ReportGenerator package project in Rstudio, and run:
```
PaRe::makeReport(pkgPath = "./", outputFile = "./Report.html")
```
it should work.
