### ISSUE TITLE
Requires cowplot to generate report

### ISSUE THREAD

**Issue by cbarbozaerasmus** [darwin-eu-dev/PaRe#24]
Hey,

The report file was generated without data. I got the following error requiring the package "cowplot":

```{r}
Error in loadNamespace(x) : there is no package called 'cowplot'
```

After I installed the package, I could generate the report for [darwin-eu-dev/ReportGenerator](https://github.com/darwin-eu-dev/ReportGenerator) and [mi-erasmusmc/Explore](https://github.com/mi-erasmusmc/Explore).

**Comment by mvankessel-EMC** [comment]
Added `cowplot` to suggests.
