### ISSUE TITLE
Github action

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PaRe#28]
Appreciate it is unlikely to be a small feature request, but having a github action to run on pull requests would be great. We'd need to think about what this would contain though (mostly around whether the pull request is adding complexity I think)

**Comment by mvankessel-EMC** [comment]
I think it would be nice to do this. The Hades repo for example uses [this](https://github.com/OHDSI/Hades/blob/main/.github/workflows/R_check_all_of_HADES.yml) yaml-file to run [this](https://github.com/OHDSI/Hades/blob/main/.github/CheckAllOfHadesFunctions.R) R-script.
