### ISSUE TITLE
addPareArticle - skip creating article directory if it already exists

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PaRe#41]
Here we try to create an articles directory
https://github.com/darwin-eu-dev/PaRe/blob/ba90a57b1b7798bb09f0384b992f902016ddda12/R/addPareArticle.R#L57

But one might already exist, as it does for PatientProfiles which then causes a warning
```
 PaRe::addPareArticle(repo = repo)
Warning message:
In dir.create(file.path(repo$getPath(), "vignettes", "articles")) :
  'D:\github\patientProfiles\PatientProfiles\vignettes\articles' already exists
```

@mvankessel-EMC  it would be good to add a check whether the articles directory exists and only create it if it doesn´t

**Comment by mvankessel-EMC** [comment]
Updated: [adfd8af](https://github.com/darwin-eu-dev/PaRe/commit/adfd8afd813b62e99cfccd2b7f9bd9c8b1a6752b)
