### ISSUE TITLE
addPareArticle - path in report (line 26)

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PaRe#42]
At the moment line 26 is created as 
`repo <- PaRe::Repository$new("D:githubpatientProfilesPatientProfiles")`

but the path on my pc should be
`"D:/github/patientProfiles/PatientProfiles"`

**Comment by edward-burn** [comment]
Could we just use "here::here()", otherwise the path in the article is going to be specific to my machine (and so other devs would have to change it for them to render the report)

**Comment by mvankessel-EMC** [comment]
Is this still an issue after the most recent commit: [adfd8af](https://github.com/darwin-eu-dev/PaRe/commit/adfd8afd813b62e99cfccd2b7f9bd9c8b1a6752b)
