### ISSUE TITLE
error on check against whitelist

### ISSUE THREAD

**Issue by ilovemane** [darwin-eu-dev/PaRe#47]
Hi @mvankessel-EMC , 

I get an error when running the check against whitelist for both patientprofiles and drugutilisation. All I did  was knitting the code from the parereport generated from PaRe::addPareArticle(repo). All other part of the checks runs fine

![image](https://github.com/darwin-eu-dev/PaRe/assets/58779940/da5257ca-f516-4baf-8a65-d7236861a504)

**Comment by mvankessel-EMC** [comment]
Looks like `pak` can't install `ggplot2`, because there is a conflict with `MASS`, which requires R >= 4.4. You could try updating R to 4.4.x

**Comment by ilovemane** [comment]
The latest R version of R is 4.3.1.

**Comment by mvankessel-EMC** [comment]
You can try to manually resolve the conflict with `MASS`, and or any other conflicts that occur with your locally installed packages.

**Comment by mvankessel-EMC** [comment]
I've looked into this further, I can't exactly figure out what changed, but I've implemented a work around. I'm planning to submit PaRe 0.1.12 to CRAN to soon. You can use the rc branch version in the mean time.

```
remotes::install_github("darwin-eu-dev/PaRe@rc")
```

**Comment by mvankessel-EMC** [comment]
@ilovemane 0.1.12 is on CRAN, let me know if it's fixed.
