### ISSUE TITLE
explanation on how to obtain a PaRe report

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/PaRe#52]
I am not sure how to perform a PaRe report. the article just shows the output, but not the code 
https://darwin-eu-dev.github.io/PaRe/articles/PareReport.html

**Comment by mvankessel-EMC** [comment]
I believe you are looking for this function: [`makeReport()`](https://darwin-eu-dev.github.io/PaRe/reference/makeReport.html).

Example:
```r
tempDir <- tempdir()
pathToRepo <- file.path(tempDir, "IncidencePrevalence")

# Clone repo
git2r::[clone](https://docs.ropensci.org/git2r/reference/clone.html)(
  url = "https://github.com/darwin-eu/IncidencePrevalence.git",
  local_path = pathToRepo
)

# Create instance of Repository object.
repo <- PaRe::Repository$new(path = pathToRepo)

makeReport(repo = repo, outputFile = tempfile())
```

**Comment by tiozab** [comment]
Thanks @mvankessel-EMC, I also found this article: 
https://github.com/darwin-eu-dev/PaRe/blob/HEAD/vignettes/articles/PareReport.Rmd

but having the function makeReport is much more easy! Thanks.
One question though: how to look at the outputFile in a nice and structured way? Right now I only see lots of files in a folder.

**Comment by mvankessel-EMC** [comment]
You can specify the `outputPath` to a file location yourself. If you set it to "pareReport.html", it will write the html-file into your current `getwd()`.

**Comment by tiozab** [comment]
@mvankessel-EMC I do not understand. 
Using your code, how can I get the report in html format?

repo <- PaRe::Repository$new(path = "C:\\Users\\tburkard\\OneDrive - Nexus365\\Documents\\GitHub\\PETDiagnostics")
makeReport(repo = repo, ... ) ?

**Comment by mvankessel-EMC** [comment]
```r
repo <- PaRe::Repository$new(path = "C:\Users\tburkard\OneDrive - Nexus365\Documents\GitHub\PETDiagnostics")
makeReport(repo = repo, "pareReport.html")
```

An example with messages:
``` r
library(PaRe)

# You don't need to do this
tempDir <- tempdir()
pathToRepo <- file.path(tempDir, "IncidencePrevalence")

# You don't need to do this
git2r::clone(
  url = "https://github.com/darwin-eu/IncidencePrevalence.git",
  local_path = pathToRepo
)
#> cloning into 'C:\Users\MVANKE~1\AppData\Local\Temp\RtmpQDUU35/IncidencePrevalence'...
#> Receiving objects:   1% (14/1346),   63 kb
#> Receiving objects:  11% (149/1346),  295 kb
#> Receiving objects:  21% (283/1346), 1080 kb
#> Receiving objects:  31% (418/1346), 1136 kb
#> Receiving objects:  41% (552/1346), 2088 kb
#> Receiving objects:  51% (687/1346), 2873 kb
#> Receiving objects:  61% (822/1346), 2929 kb
#> Receiving objects:  71% (956/1346), 6155 kb
#> Receiving objects:  81% (1091/1346), 7500 kb
#> Receiving objects:  91% (1225/1346), 8788 kb
#> Receiving objects: 100% (1346/1346), 10185 kb, done.
#> Local:    main C:/Users/mvankessel/AppData/Local/Temp/RtmpQDUU35/IncidencePrevalence
#> Remote:   main @ origin (https://github.com/darwin-eu/IncidencePrevalence.git)
#> Head:     [a4969b8] 2023-12-11: v0.6

# Create instance of Repository object.
# pathToRepo: the path where your package is located
repo <- PaRe::Repository$new(path = pathToRepo)

# repo: repo object you just created
# outputFIle: file name, with our without path
makeReport(repo = repo, outputFile = "pareReport.html")
#> 
#> Attaching package: 'plotly'
#> The following object is masked from 'package:ggplot2':
#> 
#>     last_plot
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> The following object is masked from 'package:graphics':
#> 
#>     layout
#> Linking to ImageMagick 6.9.12.93
#> Enabled features: cairo, freetype, fftw, ghostscript, heic, lcms, pango, raw, rsvg, webp
#> Disabled features: fontconfig, x11
#> processing file: report.Rmd
#> output file: report.knit.md
#> "C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/pandoc" +RTS -K512m -RTS report.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output pandoc35c87fa21e94.html --lua-filter "C:\R\R-4.3.1\library\rmarkdown\rmarkdown\lua\pagebreak.lua" --lua-filter "C:\R\R-4.3.1\library\rmarkdown\rmarkdown\lua\latex-div.lua" --embed-resources --standalone --variable bs3=TRUE --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --variable toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template "C:\R\R-4.3.1\library\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --variable theme=cosmo --mathjax --variable "mathjax-url=https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --include-in-header "C:\Users\MVANKE~1\AppData\Local\Temp\RtmpQDUU35\rmarkdown-str35c8a163b11.html"
#> 
#> Output created: C:\Users\mvankessel\AppData\Local\Temp\Rtmp8ayrH6\reprex-39241f3624c8-front-ray\pareReport.html
```

<sup>Created on 2024-01-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

As you can see it points you directly at the path where the report is located.

**Comment by tiozab** [comment]
THank you, The dependency review throughs an error 

label: checkDependencies (with options) 
List of 2
 $ echo   : logi FALSE
 $ warning: logi FALSE

Quitting from lines 164-165 (report.Rmd) 
  |..................................................................................................                        |  81%
   inline R code fragments

  |......................................................................................................                    |  84%
label: dependencyGraphStats (with options) 
List of 3
 $ echo   : logi FALSE
 $ message: logi FALSE
 $ warning: logi FALSE

Quitting from lines 173-182 (report.Rmd) 
Error in pak::pkg_deps(deps) : 
  length(pkg) == 1 && is.character(pkg) is not TRUE


Also when I run it individually from the vignette:
> DT::datatable(PaRe::checkDependencies(repo = repo, verbose = FALSE))
length(pkg) == 1 && is.character(pkg) is not TRUEThe following are not permitted: CDMConnector, checkmate, DBI, dplyr, duckdb, glue, lubridate, magrittr, misty, rlang, here, tidyr, stats, tibble, zip
Please open an issue here: https://github.com/mvankessel-EMC/DependencyReviewerWhitelists/issues

**Comment by tiozab** [comment]
@mvankessel-EMC I just tried your code, yes, I am using version 0.1.12 (same as on CRAN)
here is the reprex:
library(PaRe)
#> Warning: package 'PaRe' was built under R version 4.2.3

tempDir <- tempdir()
pathToRepo <- file.path(tempDir, "PETDiagnostics")

# Clone repo
git2r::clone(
  url = "https://github.com/oxford-pharmacoepi/PETDiagnostics.git",
  local_path = pathToRepo
)
#> cloning into 'C:\Users\tburkard\AppData\Local\Temp\RtmpgzCZ3R/PETDiagnostics'...
#> Receiving objects:   1% (5/481),   63 kb
#> Receiving objects:  11% (53/481), 1023 kb
#> Receiving objects:  21% (102/481), 1023 kb
#> Receiving objects:  31% (150/481), 1023 kb
#> Receiving objects:  41% (198/481), 1023 kb
#> Receiving objects:  51% (246/481), 1023 kb
#> Receiving objects:  61% (294/481), 1079 kb
#> Receiving objects:  71% (342/481), 1079 kb
#> Receiving objects:  81% (390/481), 1079 kb
#> Receiving objects:  91% (438/481), 1079 kb
#> Receiving objects: 100% (481/481), 1082 kb, done.
#> Local:    main C:/Users/tburkard/AppData/Local/Temp/RtmpgzCZ3R/PETDiagnostics
#> Remote:   main @ origin (https://github.com/oxford-pharmacoepi/PETDiagnostics.git)
#> Head:     [8c42bea] 2023-12-29: update CDMConnector


# Create instance of Repository object.
repo <- PaRe::Repository$new(path = pathToRepo)

makeReport(repo = repo, outputFile = "pareReport.html")
#> Warning: package 'ggplot2' was built under R version 4.2.3
#> Warning: package 'plotly' was built under R version 4.2.3
#> 
#> Attaching package: 'plotly'
#> The following object is masked from 'package:ggplot2':
#> 
#>     last_plot
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> The following object is masked from 'package:graphics':
#> 
#>     layout
#> Warning: package 'ggraph' was built under R version 4.2.3
#> Warning: package 'DT' was built under R version 4.2.2
#> Warning: package 'magick' was built under R version 4.2.3
#> Linking to ImageMagick 6.9.12.96
#> Enabled features: cairo, freetype, fftw, ghostscript, heic, lcms, pango, raw, rsvg, webp
#> Disabled features: fontconfig, x11
#> Warning: package 'withr' was built under R version 4.2.2
#> Warning: package 'cowplot' was built under R version 4.2.3
#> Warning: package 'knitr' was built under R version 4.2.2
#> Warning: package 'testthat' was built under R version 4.2.2
#> processing file: report.Rmd
#> Quitting from lines 164-165 (report.Rmd)
#> Error in pak::pkg_deps(customWhiteList$package): length(pkg) == 1 && is.character(pkg) is not TRUE
Created on 2024-01-08 with reprex v2.0.2

**Comment by mvankessel-EMC** [comment]
What version of R are you using?

**Comment by tiozab** [comment]
[1] "R version 4.2.1 (2022-06-23 ucrt)" should I update to 4.2.3?

**Comment by mvankessel-EMC** [comment]
> [1] "R version 4.2.1 (2022-06-23 ucrt)" should I update to 4.2.3?

I would try that and see if that helps.

**Comment by tiozab** [comment]
@mvankessel-EMC I updated to [1] "R version 4.3.2 (2023-10-31 ucrt)"
but the error prevails, here is the reprex

library(PaRe)

tempDir <- tempdir()
pathToRepo <- file.path(tempDir, "PETDiagnostics")

# Clone repo
git2r::clone(
  url = "https://github.com/oxford-pharmacoepi/PETDiagnostics.git",
  local_path = pathToRepo
)
#> cloning into 'C:\Users\tburkard\AppData\Local\Temp\RtmpQNqEKk/PETDiagnostics'...
#> Receiving objects:   1% (5/481),   63 kb
#> Receiving objects:  11% (53/481), 1023 kb
#> Receiving objects:  21% (102/481), 1023 kb
#> Receiving objects:  31% (150/481), 1023 kb
#> Receiving objects:  41% (198/481), 1023 kb
#> Receiving objects:  51% (246/481), 1023 kb
#> Receiving objects:  61% (294/481), 1079 kb
#> Receiving objects:  71% (342/481), 1079 kb
#> Receiving objects:  81% (390/481), 1079 kb
#> Receiving objects:  91% (438/481), 1079 kb
#> Receiving objects: 100% (481/481), 1082 kb, done.
#> Local:    main C:/Users/tburkard/AppData/Local/Temp/RtmpQNqEKk/PETDiagnostics
#> Remote:   main @ origin (https://github.com/oxford-pharmacoepi/PETDiagnostics.git)
#> Head:     [8c42bea] 2023-12-29: update CDMConnector


# Create instance of Repository object.
repo <- PaRe::Repository$new(path = pathToRepo)

makeReport(repo = repo, outputFile = "pareReport.html")
#> 
#> Attaching package: 'plotly'
#> The following object is masked from 'package:ggplot2':
#> 
#>     last_plot
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> The following object is masked from 'package:graphics':
#> 
#>     layout
#> Linking to ImageMagick 6.9.12.98
#> Enabled features: cairo, freetype, fftw, ghostscript, heic, lcms, pango, raw, rsvg, webp
#> Disabled features: fontconfig, x11
#> processing file: report.Rmd
#> 
#> Quitting from lines 164-165 [checkDependencies] (report.Rmd)
#> Error in `pak::pkg_deps()`:
#> ! length(pkg) == 1 && is.character(pkg) is not TRUE
#> Backtrace:
#>      ▆
#>   1. ├─DT::datatable(PaRe::checkDependencies(repo = repo, verbose = FALSE))
#>   2. │ └─crosstalk::is.SharedData(data)
#>   3. └─PaRe::checkDependencies(repo = repo, verbose = FALSE)
#>   4.   ├─base::suppressMessages(permittedPackages <- getDefaultPermittedPackages())
#>   5.   │ └─base::withCallingHandlers(...)
#>   6.   └─PaRe::getDefaultPermittedPackages()
#>   7.     └─base::tryCatch(...)
#>   8.       └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>   9.         ├─base (local) tryCatchOne(...)
#>  10.         │ └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  11.         └─base (local) tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
#>  12.           └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  13.             └─value[[3L]](cond)
Created on 2024-01-10 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by mvankessel-EMC** [comment]
`CodelistGenerator` was kicked off CRAN. `PaRe` was trying to look for it there, but didn't exist. I've changed it so it looks at the version on GitHub. Could you try running it again?

**Comment by tiozab** [comment]
since the version number of PaRe has not changed, you are suggesting that I use the developer version of PaRe from this repo and try again?

**Comment by mvankessel-EMC** [comment]
No, I updated the [whitelist](https://github.com/mvankessel-EMC/DependencyReviewerWhitelists/commit/879a3833dc2c6dc36aad282716881c8fe8eb226a) that `PaRe` looks at, which is separate from PaRe itself. Because it now look at the CodelistGenerator package from the darwin-eu repository, instead of the CRAN version (which does not exist anymore), I think your problem should be resolved if you try running your code again.

**Comment by tiozab** [comment]
# from Maarten

library(PaRe)

tempDir <- tempdir()
pathToRepo <- file.path(tempDir, "PETDiagnostics")

# Clone repo
git2r::clone(
  url = "https://github.com/oxford-pharmacoepi/PETDiagnostics.git",
  local_path = pathToRepo
)
#> cloning into 'C:\Users\tburkard\AppData\Local\Temp\RtmpoPkwmr/PETDiagnostics'...
#> Receiving objects:   1% (5/481),   63 kb
#> Receiving objects:  11% (53/481), 1023 kb
#> Receiving objects:  21% (102/481), 1023 kb
#> Receiving objects:  31% (150/481), 1023 kb
#> Receiving objects:  41% (198/481), 1023 kb
#> Receiving objects:  51% (246/481), 1023 kb
#> Receiving objects:  61% (294/481), 1079 kb
#> Receiving objects:  71% (342/481), 1079 kb
#> Receiving objects:  81% (390/481), 1079 kb
#> Receiving objects:  91% (438/481), 1079 kb
#> Receiving objects: 100% (481/481), 1082 kb, done.
#> Local:    main C:/Users/tburkard/AppData/Local/Temp/RtmpoPkwmr/PETDiagnostics
#> Remote:   main @ origin (https://github.com/oxford-pharmacoepi/PETDiagnostics.git)
#> Head:     [8c42bea] 2023-12-29: update CDMConnector


# Create instance of Repository object.
repo <- PaRe::Repository$new(path = pathToRepo)

makeReport(repo = repo, outputFile = "pareReport.html")
#> 
#> Attaching package: 'plotly'
#> The following object is masked from 'package:ggplot2':
#> 
#>     last_plot
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> The following object is masked from 'package:graphics':
#> 
#>     layout
#> Linking to ImageMagick 6.9.12.98
#> Enabled features: cairo, freetype, fftw, ghostscript, heic, lcms, pango, raw, rsvg, webp
#> Disabled features: fontconfig, x11
#> processing file: report.Rmd
#> 
#> Quitting from lines 164-165 [checkDependencies] (report.Rmd)
#> Error in `pak::pkg_deps()`:
#> ! length(pkg) == 1 && is.character(pkg) is not TRUE
#> Backtrace:
#>      ▆
#>   1. ├─DT::datatable(PaRe::checkDependencies(repo = repo, verbose = FALSE))
#>   2. │ └─crosstalk::is.SharedData(data)
#>   3. └─PaRe::checkDependencies(repo = repo, verbose = FALSE)
#>   4.   ├─base::suppressMessages(permittedPackages <- getDefaultPermittedPackages())
#>   5.   │ └─base::withCallingHandlers(...)
#>   6.   └─PaRe::getDefaultPermittedPackages()
#>   7.     └─base::tryCatch(...)
#>   8.       └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>   9.         ├─base (local) tryCatchOne(...)
#>  10.         │ └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  11.         └─base (local) tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
#>  12.           └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  13.             └─value[[3L]](cond)
Created on 2024-01-26 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by mvankessel-EMC** [comment]
It works for me. Could you provide me with a reprex, listing all the loaded packages?

Select Addins -> Search `reprex` -> select `Render reprex...`
![image](https://github.com/darwin-eu-dev/PaRe/assets/112690347/3c572365-0c8b-4680-9bd4-03cb8935b4fa)

Set the following options, and click `Render`
![image](https://github.com/darwin-eu-dev/PaRe/assets/112690347/e0d6ead4-1e91-47c3-b967-c15958988f7f)

You don't need to copy anything, you just need to paste it in a comment here. It will look like this:
``` r
library(PaRe)

tempDir <- tempdir()
pathToRepo <- file.path(tempDir, "PETDiagnostics")

git2r::clone(
  url = "https://github.com/oxford-pharmacoepi/PETDiagnostics.git",
  local_path = pathToRepo
)
#> cloning into 'C:\Users\MVANKE~1\AppData\Local\Temp\RtmpOqZMoe/PETDiagnostics'...
#> Receiving objects:   1% (5/481),   63 kb
#> Receiving objects:  11% (53/481), 1023 kb
#> Receiving objects:  21% (102/481), 1023 kb
#> Receiving objects:  31% (150/481), 1023 kb
#> Receiving objects:  41% (198/481), 1023 kb
#> Receiving objects:  51% (246/481), 1023 kb
#> Receiving objects:  61% (294/481), 1079 kb
#> Receiving objects:  71% (342/481), 1079 kb
#> Receiving objects:  81% (390/481), 1079 kb
#> Receiving objects:  91% (438/481), 1079 kb
#> Receiving objects: 100% (481/481), 1082 kb, done.
#> Local:    main C:/Users/mvankessel/AppData/Local/Temp/RtmpOqZMoe/PETDiagnostics
#> Remote:   main @ origin (https://github.com/oxford-pharmacoepi/PETDiagnostics.git)
#> Head:     [8c42bea] 2023-12-29: update CDMConnector

repo <- PaRe::Repository$new(path = pathToRepo)

makeReport(repo = repo, outputFile = "pareReport.html")
#> 
#> Attaching package: 'plotly'
#> The following object is masked from 'package:ggplot2':
#> 
#>     last_plot
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> The following object is masked from 'package:graphics':
#> 
#>     layout
#> Linking to ImageMagick 6.9.12.93
#> Enabled features: cairo, freetype, fftw, ghostscript, heic, lcms, pango, raw, rsvg, webp
#> Disabled features: fontconfig, x11
#> Warning: package 'knitr' was built under R version 4.3.2
#> processing file: report.Rmd
#> output file: report.knit.md
#> "C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/pandoc" +RTS -K512m -RTS report.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output pandoc8884226a814.html --lua-filter "C:\R\R-4.3.1\library\rmarkdown\rmarkdown\lua\pagebreak.lua" --lua-filter "C:\R\R-4.3.1\library\rmarkdown\rmarkdown\lua\latex-div.lua" --embed-resources --standalone --variable bs3=TRUE --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --variable toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template "C:\R\R-4.3.1\library\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --variable theme=cosmo --mathjax --variable "mathjax-url=https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --include-in-header "C:\Users\MVANKE~1\AppData\Local\Temp\RtmpOqZMoe\rmarkdown-str888457ff2981.html"
#> 
#> Output created: C:\Users\mvankessel\AppData\Local\Temp\RtmpUPd1VK\reprex-35f0e7376f3-hexed-tuna\pareReport.html
```

<sup>Created on 2024-02-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16 ucrt)
#>  os       Windows 11 x64 (build 22621)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  Dutch_Netherlands.utf8
#>  ctype    Dutch_Netherlands.utf8
#>  tz       Europe/Amsterdam
#>  date     2024-02-02
#>  pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package       * version date (UTC) lib source
#>  backports       1.4.1   2021-12-13 [1] CRAN (R 4.3.0)
#>  brio            1.1.3   2021-11-30 [1] CRAN (R 4.3.1)
#>  bslib           0.5.1   2023-08-11 [1] CRAN (R 4.3.1)
#>  cachem          1.0.8   2023-05-01 [1] CRAN (R 4.3.1)
#>  callr           3.7.3   2022-11-02 [1] CRAN (R 4.3.1)
#>  checkmate       2.3.0   2023-10-25 [1] CRAN (R 4.3.2)
#>  cli             3.6.1   2023-03-23 [1] CRAN (R 4.3.1)
#>  codetools       0.2-19  2023-02-01 [1] CRAN (R 4.3.1)
#>  colorspace      2.1-0   2023-01-23 [1] CRAN (R 4.3.1)
#>  cowplot       * 1.1.1   2020-12-30 [1] CRAN (R 4.3.1)
#>  crayon          1.5.2   2022-09-29 [1] CRAN (R 4.3.1)
#>  crosstalk       1.2.0   2021-11-04 [1] CRAN (R 4.3.1)
#>  curl            5.0.1   2023-06-07 [1] CRAN (R 4.3.1)
#>  cyclocomp       1.1.0   2016-09-10 [1] CRAN (R 4.3.1)
#>  data.table      1.14.8  2023-02-17 [1] CRAN (R 4.3.1)
#>  desc            1.4.2   2022-09-08 [1] CRAN (R 4.3.1)
#>  DiagrammeR      1.0.10  2023-05-18 [1] CRAN (R 4.3.1)
#>  DiagrammeRsvg   0.1     2016-02-04 [1] CRAN (R 4.3.1)
#>  digest          0.6.33  2023-07-07 [1] CRAN (R 4.3.1)
#>  dplyr           1.1.2   2023-04-20 [1] CRAN (R 4.3.1)
#>  DT            * 0.28    2023-05-18 [1] CRAN (R 4.3.1)
#>  ellipsis        0.3.2   2021-04-29 [1] CRAN (R 4.3.1)
#>  evaluate        0.21    2023-05-05 [1] CRAN (R 4.3.1)
#>  fansi           1.0.4   2023-01-22 [1] CRAN (R 4.3.1)
#>  farver          2.1.1   2022-07-06 [1] CRAN (R 4.3.1)
#>  fastmap         1.1.1   2023-02-24 [1] CRAN (R 4.3.1)
#>  fs              1.6.3   2023-07-20 [1] CRAN (R 4.3.1)
#>  generics        0.1.3   2022-07-05 [1] CRAN (R 4.3.1)
#>  ggforce         0.4.1   2022-10-04 [1] CRAN (R 4.3.1)
#>  ggplot2       * 3.4.3   2023-08-14 [1] CRAN (R 4.3.1)
#>  ggraph        * 2.1.0   2022-10-09 [1] CRAN (R 4.3.1)
#>  ggrepel         0.9.3   2023-02-03 [1] CRAN (R 4.3.1)
#>  git2r           0.32.0  2023-04-12 [1] CRAN (R 4.3.1)
#>  glue            1.6.2   2022-02-24 [1] CRAN (R 4.3.1)
#>  graphlayouts    1.0.0   2023-05-01 [1] CRAN (R 4.3.1)
#>  gridExtra       2.3     2017-09-09 [1] CRAN (R 4.3.1)
#>  gtable          0.3.3   2023-03-21 [1] CRAN (R 4.3.1)
#>  highr           0.10    2022-12-22 [1] CRAN (R 4.3.1)
#>  htmltools       0.5.6   2023-08-10 [1] CRAN (R 4.3.1)
#>  htmlwidgets     1.6.2   2023-03-17 [1] CRAN (R 4.3.1)
#>  httr            1.4.7   2023-08-15 [1] CRAN (R 4.3.1)
#>  igraph          1.5.0   2023-06-16 [1] CRAN (R 4.3.1)
#>  jquerylib       0.1.4   2021-04-26 [1] CRAN (R 4.3.1)
#>  jsonlite        1.8.7   2023-06-29 [1] CRAN (R 4.3.1)
#>  knitr         * 1.45    2023-10-30 [1] CRAN (R 4.3.2)
#>  labeling        0.4.2   2020-10-20 [1] CRAN (R 4.3.0)
#>  lazyeval        0.2.2   2019-03-15 [1] CRAN (R 4.3.1)
#>  lifecycle       1.0.3   2022-10-07 [1] CRAN (R 4.3.1)
#>  lintr           3.0.2   2022-10-19 [1] CRAN (R 4.3.1)
#>  magick        * 2.7.5   2023-08-07 [1] CRAN (R 4.3.1)
#>  magrittr        2.0.3   2022-03-30 [1] CRAN (R 4.3.1)
#>  MASS            7.3-60  2023-05-04 [1] CRAN (R 4.3.1)
#>  munsell         0.5.0   2018-06-12 [1] CRAN (R 4.3.1)
#>  pak             0.5.1   2023-04-27 [1] CRAN (R 4.3.1)
#>  PaRe          * 0.1.12  2023-08-11 [1] CRAN (R 4.3.1)
#>  pillar          1.9.0   2023-03-22 [1] CRAN (R 4.3.1)
#>  pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 4.3.1)
#>  plotly        * 4.10.2  2023-06-03 [1] CRAN (R 4.3.1)
#>  polyclip        1.10-4  2022-10-20 [1] CRAN (R 4.3.0)
#>  processx        3.8.2   2023-06-30 [1] CRAN (R 4.3.1)
#>  ps              1.7.5   2023-04-18 [1] CRAN (R 4.3.1)
#>  purrr           1.0.1   2023-01-10 [1] CRAN (R 4.3.1)
#>  R.cache         0.16.0  2022-07-21 [1] CRAN (R 4.3.1)
#>  R.methodsS3     1.8.2   2022-06-13 [1] CRAN (R 4.3.0)
#>  R.oo            1.25.0  2022-06-12 [1] CRAN (R 4.3.0)
#>  R.utils         2.12.2  2022-11-11 [1] CRAN (R 4.3.1)
#>  R6              2.5.1   2021-08-19 [1] CRAN (R 4.3.1)
#>  RColorBrewer    1.1-3   2022-04-03 [1] CRAN (R 4.3.0)
#>  Rcpp            1.0.11  2023-07-06 [1] CRAN (R 4.3.1)
#>  remotes         2.4.2.1 2023-07-18 [1] RSPM (R 4.3.0)
#>  reprex          2.0.2   2022-08-17 [1] CRAN (R 4.3.1)
#>  rex             1.2.1   2021-11-26 [1] CRAN (R 4.3.1)
#>  rlang           1.1.1   2023-04-28 [1] CRAN (R 4.3.1)
#>  rmarkdown       2.24    2023-08-14 [1] CRAN (R 4.3.1)
#>  rprojroot       2.0.3   2022-04-02 [1] CRAN (R 4.3.1)
#>  rstudioapi      0.15.0  2023-07-07 [1] CRAN (R 4.3.1)
#>  rsvg            2.4.0   2022-11-21 [1] CRAN (R 4.3.1)
#>  sass            0.4.7   2023-07-15 [1] CRAN (R 4.3.1)
#>  scales          1.2.1   2022-08-20 [1] CRAN (R 4.3.1)
#>  sessioninfo     1.2.2   2021-12-06 [1] CRAN (R 4.3.1)
#>  stringi         1.7.12  2023-01-11 [1] CRAN (R 4.3.0)
#>  stringr         1.5.0   2022-12-02 [1] CRAN (R 4.3.1)
#>  styler          1.10.1  2023-06-05 [1] CRAN (R 4.3.1)
#>  testthat      * 3.1.10  2023-07-06 [1] CRAN (R 4.3.1)
#>  tibble          3.2.1   2023-03-20 [1] CRAN (R 4.3.1)
#>  tidygraph       1.2.3   2023-02-01 [1] CRAN (R 4.3.1)
#>  tidyr           1.3.0   2023-01-24 [1] CRAN (R 4.3.1)
#>  tidyselect      1.2.0   2022-10-10 [1] CRAN (R 4.3.1)
#>  tweenr          2.0.2   2022-09-06 [1] CRAN (R 4.3.1)
#>  utf8            1.2.3   2023-01-31 [1] CRAN (R 4.3.1)
#>  V8              4.3.3   2023-07-18 [1] CRAN (R 4.3.1)
#>  vctrs           0.6.3   2023-06-14 [1] CRAN (R 4.3.1)
#>  viridis         0.6.3   2023-05-03 [1] CRAN (R 4.3.1)
#>  viridisLite     0.4.2   2023-05-02 [1] CRAN (R 4.3.1)
#>  visNetwork      2.1.2   2022-09-29 [1] CRAN (R 4.3.1)
#>  withr         * 2.5.0   2022-03-03 [1] CRAN (R 4.3.1)
#>  xfun            0.40    2023-08-09 [1] CRAN (R 4.3.1)
#>  xml2            1.3.5   2023-07-06 [1] CRAN (R 4.3.1)
#>  xmlparsedata    1.0.5   2021-03-06 [1] CRAN (R 4.3.1)
#>  yaml            2.3.7   2023-01-23 [1] CRAN (R 4.3.0)
#> 
#>  [1] C:/R/R-4.3.1/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by tiozab** [comment]
I use reprex I dont know why it does not depict as nicely as yours, I just copy paste what is in the reprex

**Comment by mvankessel-EMC** [comment]
> I use reprex I dont know why it does not depict as nicely as yours, I just copy paste what is in the reprex

Reprex automatically puts the formatted output on the clipboard, so you don't need to copy anything, just paste it. But thank you!

**Comment by mvankessel-EMC** [comment]
Could you try the following unstalling `pak` version 0.5.1?
```r
remotes::install_version(package = "pak", version = "0.5.1")
```

And then try again? It seems like they changed something with a function I'm using.
