### ISSUE TITLE
makeReport not working

### ISSUE THREAD

**Issue by PRijnbeek** [darwin-eu-dev/PaRe#58]
Running your example from the other issue:

tempDir <- tempdir()
pathToRepo <- file.path(tempDir, "IncidencePrevalence")

# Clone repo
git2r::clone(
  url = "https://github.com/darwin-eu/IncidencePrevalence.git",
  local_path = pathToRepo
)

# Create instance of Repository object.
repo <- PaRe::Repository$new(path = pathToRepo)

makeReport(repo = repo, outputFile = tempfile())

---> ERROR

How can this pass your unit tests?

Version PaRe: 0.1.12 installed from CRAN

processing file: report.Rmd
  |......................................................................                     |  77% [checkDependencies]     
Quitting from lines 164-165 [checkDependencies] (report.Rmd)
Error in `pak::pkg_deps()`:
! length(pkg) == 1 && is.character(pkg) is not TRUE
Backtrace:
  1. DT::datatable(PaRe::checkDependencies(repo = repo, verbose = FALSE))
  3. PaRe::checkDependencies(repo = repo, verbose = FALSE)
  6. PaRe::getDefaultPermittedPackages()
  7. base::tryCatch(...)
  8. base (local) tryCatchList(expr, classes, parentenv, handlers)
 11. base (local) tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
 12. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 13. value[[3L]](cond)

**Comment by mvankessel-EMC** [comment]
For now you can install the `rc` branch (this is the branch I'm submitting to CRAN).

```r
remotes::install_github("darwin-eu-dev/PaRe@rc")
```

I have been working on a new release.

**Comment by PRijnbeek** [comment]
That works.
